### ISSUE TITLE
Migrate List to react-virtualized implementation

### ISSUE THREAD

**Issue by jsomsanith** [Talend/ui#537]
This issue is to have a progress on the react-virtualized List topic.

**Issues**
- [x] IE11 Large display issue @jare-talend https://github.com/Talend/ui/pull/565
- [x]  Large table after the deleting of the research, the rows are not reinitialized @jare-talend https://github.com/Talend/ui/pull/595
- [x] Update react-virtualized when the fix on scroll will be available https://github.com/bvaughn/react-virtualized/issues/722 https://github.com/Talend/ui/pull/731

**Stories**
- [x] (@jmfrancois #504) Migrate stories on column action
- [x] (@jare-talend #573) Migrate stories on toolbar (easy and straighforward) 
- [x] (@jsomsanith #535) Migrate stories on sort
- [x] (@jare-talend #576) Migrate stories on empty list
- [x] (@jsomsanith #625) Migrate story on selection + drop custom selection classname since no one seem to use it
- [ ] ~~Migrate stories on ellipsis (or drop it since this is native to virtualized ?)~~ Don't migrate it, it is native
- [ ] ~~Migrate stories on scroll (or drop it since this is native to virtualized ?)~~ Don't migrate it, it is native

**POC**
- [x] POC on tiles to ensure there is no technical blocking issue @jare-talend https://github.com/Talend/ui/pull/588

**QA**
- [x] See with QA of each project about the impact of migrating to the new implementation
* TFD: use old version of component-object, should be easy
* TDP: duplication of selectors, should be painfull, need to prepare code before switching
* TDS: waiting for QA holidays return
* TMC: asked Neiven, waiting for answer
* TIC: asked Neiven, waiting for answer
- [x] (@jsomsanith #634) Update the components-object

**Usage**
- [x] Enable flag on TDP (https://jira.talendforge.org/browse/TDP-4314)
- [x] Enable flag on TFD (https://jira.talendforge.org/browse/TFD-2022)
- [x] Enable flag on TDS (https://jira.talendforge.org/browse/TDS-2636)
- [x] Enable flag on TMC (https://jira.talendforge.org/browse/TMC-11122)
- [x] Enable flag on TIC (https://jira.talendforge.org/browse/TIPAAS-11071)

**Clean**
- [x] Remove all the other implementations

**Comment by jsomsanith** [comment]
Completed 🎉
