### ISSUE TITLE
Migrate forms to the new implementation

### ISSUE THREAD

**Issue by jsomsanith-tlnd** [Talend/ui#538]
A new form implementation has started with #415.
This issue is to follow the progress on this Form topic.

**Features**
- [x] (#544) Implement FieldTemplate to avoid to add Message element each time
- [ ] ~~Multi-widgets per row [see @glorieux's PR on old forms](https://github.com/Talend/ui/pull/542)~~ (will be supported by columns)
- [x] (#594 need review) Modify `onChange(event, schema, value)` to `onChange(event, payload)`
- [x] (#721) Add classname support (see #693)
- [x] (#729) Fix : Objects need to be init in properties. We should be able to pass nothing
- [ ] With async validation, we need a way to say to forms that it has no error, so it can delete the current error it has on a field. For now we have to pass to the forms `{ errors: {'my.field.key`: undefined}}`
- [x] (#1009) Conditional render
- [ ] trigger in progress flags by input

**Fields**
- [x] (#694) Implement password
- [x] (#547) Implement textarea
- [x] (#548) Implement checkbox
- [x] (#548) Implement checkboxes
- [x] (#651) Implement array
- [x] (#993) Add title on arrays
- [ ] Array customize text in add button (look at ##676)
- [x] (#883) Array Collapse previous array items on add (look at #695)
- [x] (#517) Implement select
- [x] (#555) Implement radios
- [x] (#558) Implement submit, reset, actions buttons

**Custom widgets**
- [x] (#615) Migrate Column widget
- [x] (#671) Migrate Datalist widget
- [ ] Migrate Enumeration widget
- [x] (#743) Migrate KeyValue widget
- [x] (#747) Migrate ListView widget
- [x] (#714) Migrate MultiSelectTag widget
- [ ] MultiSelectTag categories
- [x] (#665) Migrate RadioOrSelectWidget widget (is it really used ?)
- [x] (#662) Migrate Toggle widget
- [x] (#881) Migrate CollapsibleFieldset + Array display remove icon when item isClosed (look at #678)

**Optional**
- [ ] Datalist: Customize items load (in old Datalist : formContext.fetchItems). Find a solution that will match Select dynamic loading too
- [ ] ListView : Customize filter (in old ListView : formContext.handleAction) (? not used for now)
- [ ] ListView : implement disabled (? or just let it like that, not currently supported)

**Docs**
- [x] (#579) Reorganise field/fieldsets into folders so that each element can have its README
- [x] (#607) Write the fields/fieldsets user documentation as a README file for each

**UX**
- [ ] Implement the last UX guideline on forms
- [ ] Talk to UX about message/errors messages [see @acateland's comment](https://github.com/Talend/ui/pull/544#pullrequestreview-44777431)

**Daikon**
- [ ] See with Daikon to change the serializer

**Migration**
- [ ] Determine a migration path for TCOMP
- [ ] Determine a migration path for pure frontend forms
- [ ] Understand the apps specific changes use cases + make them use Daikkon POJO/serializer
- [ ] Wizard (work with @sgandon, optional for migration but need to be done)

**Comment by acateland** [comment]
array need to be implemented they are indeed used.
Also
a complex case arise.
We need an array like structure, with object who on each i could trigger update of a list, meaning that each object in an array may be displaying for the same component a different set of element in a list, meaning also those field should check agains those differents element, maybe it should be done trough another construct ?
